### ISSUE TITLE
Question how to exit the container?

### ISSUE THREAD

**Issue by pascalandy** [pitrho/docker-host-stats#1]
see the screen
Thanks!

![screenr 2016-04-13 at 8 07 19 am](https://cloud.githubusercontent.com/assets/6694151/14492658/d27f62fa-014e-11e6-822f-bfc001e353bf.jpg)

**Comment by pascalandy** [comment]
I opened a new terminal window and docker stop from there. This is it ?

**Comment by thegalexc** [comment]
That's correct -- when you run the command directly as it is in the documentation you're not going to be able to `ctrl-c` out of it. If you would like to be able to detach from the container then you can add the `-t` flag to allocate a pseudo-TTY. In that case, when you hit `ctrl-c` you will exit that TTY but the process will continue to run. To stop and remove the process itself you will need to run

```
docker ps
docker stop {{container id}}
docker rm {{container id}}
```

(or `docker rm -f {{container id}}`). Some reference is here: https://docs.docker.com/engine/reference/run/ in the "Foreground" section.
